### ISSUE TITLE
Application closes/crashes 

### ISSUE THREAD

**Issue by Hristijan95** [ramilushev/react-native-background-color#12]
I've implemented the library, it looks like a very simple implementation, however, my applications (both iOS and Android) are just closing on the `BackgroundColor.setColor('#FFFFFF');` line. 

There is nothing printed, no error, nothing. Any ideas why?

**Comment by Hristijan95** [comment]
I've installed it from scratch with clear cache and it works now, so it was me.

**Comment by muhsin-k** [comment]
@Hristijan95 I am getting the same issue. I uninstalled the app and build again. But nothing changed. Could you please explain what are the steps you did?

**Comment by Hristijan95** [comment]
> @Hristijan95 I am getting the same issue. I uninstalled the app and build again. But nothing changed. Could you please explain what are the steps you did?

Hi, I've discovered the cause of the crash after I posted this. I was sending rgb(255, 255, 255) in the setColor function, instead of #ffffff.

So, I've replacet this `BackgroundColor.setColor('rgb(255, 255, 255)');` with this `BackgroundColor.setColor('#FFFFFF');`
